#!/usr/bin/env bash
set -euo pipefail

# rotate_bot_proxy_key.sh
# Generates a new BOT_PROXY_KEY, updates .env (local), and prints Choreo update instructions + test curl.

ENV_FILE="${1:-.env}"
PROXY_TEST_ENDPOINT="${2:-}"   # optional: e.g. https://<your-proxy>.choreo.run/v1/generate
OLD_KEY_HINT="${3:-}"          # optional human hint for old key (not used programmatically)

# 1) generate a new strong key (48 hex chars)
NEW_KEY="$(openssl rand -hex 32)"

# 2) update local .env (create if missing). Keep other entries intact.
if [ -f "$ENV_FILE" ]; then
  # replace existing BOT_PROXY_KEY or append
  if grep -q '^BOT_PROXY_KEY=' "$ENV_FILE"; then
    sed -i.bak -E "s/^BOT_PROXY_KEY=.*/BOT_PROXY_KEY=${NEW_KEY}/" "$ENV_FILE"
    echo "Updated BOT_PROXY_KEY in ${ENV_FILE} (backup at ${ENV_FILE}.bak)"
  else
    echo "BOT_PROXY_KEY=${NEW_KEY}" >> "$ENV_FILE"
    echo "Appended BOT_PROXY_KEY to ${ENV_FILE}"
  fi
else
  cat > "$ENV_FILE" <<EOF
# Generated by rotate_bot_proxy_key.sh
BOT_PROXY_KEY=${NEW_KEY}
EOF
  echo "Created ${ENV_FILE} with BOT_PROXY_KEY"
fi

# 3) output instructions for Choreo (manual paste) and verification
cat <<EOF

NEW BOT_PROXY_KEY GENERATED
---------------------------
New key:
  ${NEW_KEY}

Local file updated: ${ENV_FILE}

IMPORTANT: Now update the BOT_PROXY_KEY secret in your Choreo services:
  - animous-proxy (secret name: BOT_PROXY_KEY)
  - animous-bot   (secret name: BOT_PROXY_KEY)
  - animous-core  (secret name: BOT_PROXY_KEY)

Steps (manual):
  1) Open Choreo → Services → animous-proxy → Secrets → Edit BOT_PROXY_KEY and paste the new key.
  2) Repeat for animous-bot and animous-core.
  3) Redeploy or restart each service so they pick up the new secret.

Optional: if you want to perform a quick smoke test of the proxy AFTER updating the Choreo secret and redeploying, run this curl (replace placeholders):

  curl -X POST "<PROXY_URL>" \\
    -H "Content-Type: application/json" \\
    -H "X-Bot-Proxy-Key: ${NEW_KEY}" \\
    -d '{"prompt":"Hello test"}'

If you do not have the proxy URL at hand, the proxy test endpoint placeholder is:
  ${PROXY_TEST_ENDPOINT:-<your-proxy-URL-here>}

Safe rotation tips:
  - Do NOT remove the old key from services until all services show successful connection with the new key.
  - If you can, create a short overlap window: add new secret value to each service (or add a second secret name if Choreo supports), restart, verify, then remove the old one.
  - Rotate and store the new key in your password manager.

If you want the script to attempt automatic updates via a Choreo API or CLI, provide your Choreo API endpoint and an auth token and I can extend the script to call the Choreo API to rotate secrets programmatically.
EOF
